#!/usr/bin/env bash
# Bash script that displays umbers from 1 to 100
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format
n=1
while (( n <= 100 ))
do
	if (( n % 5 == 0 )) && (( n % 3 == 0 ));
	then
		echo "FizzBuzz"
	elif (( n % 5 == 0 ));
	then
		echo "Buzz"
	elif (( n % 3 == 0));
	then
		echo "Fizz"
	else
		echo $n
	fi
	((n++))
done
