#!/usr/bin/env bash
# Bash script that displays Best School 10 timesand Hi in a new line
# using while loop and if statement
n=0
while [[ $n -lt 10 ]]
do
	if [[ $n -eq 9 ]];
	then
		echo "Hi"
	fi
		echo "Best School"
	((n++))
done
