#!/usr/bin/env bash
# Bash script that loops 1 to 10
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iteration
n=1
while (( n <= 10 ))
do
	if [[ "$n" == '4' ]];
	then
		echo "bad luck"
	elif [[ "$n" == '8' ]];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
		((n++))
done
