#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
# using while loop and case statement
n=0
while (( n <= 19 ))
do
	((n++))
	case $n in
		"4") echo -e "$n\nbad luck from China";;
		"9") echo -e "$n\nbad luck from Japan";;
		"17") echo -e "$n\nbad luck from Italy";;
		*) echo $n;;
	esac
done
