#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
n=0
while (( n <= 12 ))
do
	echo "Hour: $n"
		m=1
		while (( m <= 59 ))
		do
			echo $m
			((m++))
		done
	((n++))
done
